### ISSUE TITLE
Put space in between buttons on "links" page

### ISSUE THREAD

**Issue by WoodwardIII-HS** [Team236/team236.github.io#3]
My CSS is not working.
![Image 10-10-24 at 10 18 AM](https://github.com/user-attachments/assets/fbe3ffff-d25b-4ccd-877f-bf5567d1f202)

**Comment by ko-sako** [comment]
I have submitted a pull request related to this issue. Please take a look when you have a chance. Thank you!

**Comment by WoodwardIII-HS** [comment]
Thank you for fixing my code(I was really confused as CSS is not my forte). I will merge it as soon as I get home.
